### ISSUE TITLE
Find an additional case study, and write TLA+ monitors for it

### ISSUE THREAD

**Issue by andrey-kuprianov** [freespek/solarkraft#13]
Currently we have a single case study, [a manual demo with the Timelock contract](https://github.com/freespek/solarkraft/tree/main/doc/scf24/example). We need to identify 2-3 additional case studies from [soroban-examples](https://github.com/stellar/soroban-examples/tree/main), and write specifications for them in the form of TLA+ monitors. 

This is the first stage for the above, with only 1 additional case study. This issue is completed when:

- [x] 1 additional case study contract is identified;
   - ~[Liquidity pool contract](https://github.com/stellar/soroban-examples/blob/main/liquidity_pool/src/lib.rs): non-trivial, with interesting properties.~: this is for the second case study
   - [Token contract](https://github.com/stellar/soroban-examples/blob/main/token/src/lib.rs): sufficiently complex for the first pass.
- [ ] inner workings of the contract are understood and documented;
- [ ] correctness properties  of the contract are formulated;
- [ ] correctness properties are encoded as a composition of (simple) TLA+ monitors.

**Comment by thpani** [comment]
Closing this in favor of #136 

@andrey-kuprianov If you wish to contribute another case study, this is very welcome!
