### ISSUE TITLE
Develop more stable integration tests for the transaction fetcher

### ISSUE THREAD

**Issue by konnov** [freespek/solarkraft#56]
As noted in #55, the integration test may stop working when the contract ledger history disappears, due to a TTL, or due to a testnet reset. We need an integration test that populates the network with data and then evaluates it. One blocker towards that is that [Stellar binaries](https://github.com/stellar/binaries/), used in Github actions, are not supporting v21 yet.

**Comment by thpani** [comment]
We could probably install our own, based on the upstream [`build.yml`](https://github.com/stellar/binaries/blob/main/.github/workflows/build.yml)
