### ISSUE TITLE
Installation breaks on Linux

### ISSUE THREAD

**Issue by andrey-kuprianov** [freespek/solarkraft#78]
The problem seems to be specific to either Linux in general, or to my specific setup (Ubuntu 22.04.4 LTS, node v20.13.1, npm  10.5.2).

When trying to follow the instructions in [CONTRIBUTING](https://github.com/freespek/solarkraft/blob/bc675c97f990dd2ab2618448e18c437ea65ad9ac/CONTRIBUTING.md) or [INSTALL](https://github.com/freespek/solarkraft/blob/bc675c97f990dd2ab2618448e18c437ea65ad9ac/solarkraft/INSTALL.md) the process breaks for me at executing `npm link`:

```
npm ERR! code 1
npm ERR! path ~/solarkraft/solarkraft
npm ERR! command failed
npm ERR! command sh -c cd .. && husky solarkraft/.husky
```
I figured out that I can solve that via removing, or assigning the empty string to the [prepare script](https://github.com/freespek/solarkraft/blob/bc675c97f990dd2ab2618448e18c437ea65ad9ac/solarkraft/package.json#L38). This is obviously not a great solution, so we need to figure out a better one, which works on all platforms.

**Comment by thpani** [comment]
Hmmm, it works fine in my devcontainer, which is Debian.

I assume you did `npm install` first?

If you run `npm run prepare` (with the script commented in, of course), does it work?

**Comment by thpani** [comment]
I will close this - if this occurs again please reopen or file a fresh issue
